---
- name: Deploy to K8s Cluster
  hosts: webservers  
  
  tasks:
    - name: clone repository
      git: >
        repo=ssh://git@github.com:arulhub/kub-dep-tasks.git          
        dest=/opt/kub-demo
    - name: Deploy tasks API
      shell: |
        kubectl apply -f=/opt/kub-demo/tasks.yaml